### ISSUE TITLE
New model changes break code

### ISSUE THREAD

**Issue by simon-rob** [wlguan/Stronger-yolo-pytorch#6]
I get:

simon@simon-ubuntu:/hdd1/Stronger-yolo-pytorch$ python3.7 main.py --config-file configs/bdd.yaml  EXPER.experiment_name bdd_512 devices 0,
successfully load ckpt mobilev2
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    main(args=cfg)
  File "main.py", line 23, in main
    net = eval(cfg.MODEL.modeltype)(cfg=args.MODEL).cuda()
  File "/hdd1/Stronger-yolo-pytorch/models/yolov3.py", line 22, in __init__
    ('conv5',sepconv_bn(512,1024,kernel=3, stride=1, padding=1,seprelu=cfg.sepreluvvvvvvvvv)),
  File "/usr/local/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: sepreluvvvvvvvvv

Should it be cfg.seprelu not cfg.sepreluvvvvvvvvv?

Regards,

Simon

**Comment by wlguan** [comment]
@simon-rob Hi, typo fixed. Sorry for the confusion.
